apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.NOMBRE_APP }}-k8
spec:
  replicas: {{ .Values.REPLICAS }}
  selector:
    matchLabels:
      app: {{ .Values.NOMBRE_APP }}-k8
  template:
    metadata:
      labels:
        app: {{ .Values.NOMBRE_APP }}-k8
    spec:
      containers:
      - name: {{ .Values.NOMBRE_APP }}-k8
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: {{ .Values.PORT }}
        env:
        - name: MESSAGE
          value: "{{ .Values.MESSAGE }}"
        - name: PORT
          value: "{{ .Values.PORT }}"
