apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.NOMBRE_APP }}-k8
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.PORT }}
  selector:
    app: {{ .Values.NOMBRE_APP }}-k8
